name: Auto-publish daily worksheets

on:
  schedule:
    - cron: "0 11 * * *"   # 11:00 UTC every day; change this if you want
  workflow_dispatch: {}     # lets you run it manually

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

- name: Generate worksheets
  env:
    PYTHONPATH: scripts
  run: |
    python scripts/gen_word_ladder.py
    python scripts/gen_math_mixed_g2.py


      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-publish worksheets: $(date -u +%Y-%m-%d)"
            git push
          fi
